### ISSUE TITLE
Second example for journeys in the docs does not work

### ISSUE THREAD

**Issue by tobysoby** [derhuerst/db-rest#10]
Hey, thanks for these great APIs! Just a very small heads-up, the second example for journeys does not work until an id is added, like you already mentioned in the documentation. So, instead of 
> curl 'https://2.db.transport.rest/journeys?from=008004158&to.name=Atze%20Musiktheater&to.latitude=52.543333&to.longitude=13.351686'

it should be
> curl 'https://2.db.transport.rest/journeys?from=008004158&to.name=Atze%20Musiktheater&to.latitude=52.543333&to.longitude=13.351686&to.id=991598902'

Just mentioning it because it took me a minute to find out why it's not working... :-)

**Comment by derhuerst** [comment]
Thanks!
