### ISSUE TITLE
Stations by Location is broken

### ISSUE THREAD

**Issue by jeyemwey** [derhuerst/db-rest#13]
When requesting stations by their location (e.g. `http://localhost:3000/stations?coordinates.latitude=50.1041&coordinates.longitude=8.657`), db-rest returns all 5368 locations in the system A to Z.

How can you just search by stations around some given coordinates?

**Comment by derhuerst** [comment]
Thanks for reporting! I assume you're running `master`/`3`, not `2`?

**Comment by jeyemwey** [comment]
Version 3, yes.

On Jan 31, 2020 2:39 PM, Jannis Redmann <notifications@github.com> wrote:

Thanks for reporting! I assume you're running master/3, not 2?

**Comment by derhuerst** [comment]
This is a mess. 💩

There's another bug in `db-stations`, fixed as of https://github.com/derhuerst/db-stations/commit/219ace5c8fef69ff288bf3595e78427e1df98a14, but not published yet.
