### ISSUE TITLE
deploy 3.db.transport.rest with hafas-client@5

### ISSUE THREAD

**Issue by petabyteboy** [derhuerst/db-rest#14]

**Comment by derhuerst** [comment]
Thanks for reporting!

This happens because the underlying `hafas-client@3` (which is old) adds `ealierRef` & `laterRef` to the *array* of journeys, which JSON does not support.

The easiest, but backwards-incompatible, fix would probably do upgrade `hafas-rest-api` and therefore `db-rest` to use `hafas-client@5`.

**Comment by petabyteboy** [comment]
Okay, I thought it had also been fixed in db-rest at some point.
I'm using hafas-rest-api with the db profile for now. I think it is not easily fixable without a backwards-incompatible change.
So it would be nice to see 3.db.transport.rest with this change at some point, because being able to use a hosted version for development of my application would be very convenient.

**Comment by derhuerst** [comment]
> Okay, I thought it had also been fixed in db-rest at some point.

Not sure, maybe I forgot about it.

> I'm using `hafas-rest-api` with the db profile for now. [...] So it would be nice to see `3.db.transport.rest` with this change at some point, because being able to use a hosted version for development of my application would be very convenient.

Yes, I fully agree! Although these hosted & unauthenticated APIs are probably quite valuable to people, I haven't maintained them well so far.

My priorities are different right now: Building a new kind of API that

- combines multiple data sources (see [`pan-european-public-transport`](https://github.com/derhuerst/pan-european-public-transport) and [`find-hafas-leg-in-another-hafas`](https://github.com/derhuerst/find-hafas-leg-in-another-hafas) for prototypes)
- has built-in caching & offline/retrying support
- provides subscription mechanisms for realtime data, e.g. [SSE](https://en.wikipedia.org/wiki/Server-sent_events) or WebSockets
- abstracts more over vendor- and data-source-specific quirks

**Comment by derhuerst** [comment]
I've forgotten about this. [`v5.db.transport.rest`](https://v5.db.transport.rest/) is deployed by now and uses `hafas-client@5` underneath.
