### ISSUE TITLE
Get Departures: 'stopovers' doen't work

### ISSUE THREAD

**Issue by jonaskl99** [derhuerst/db-rest#18]
Example request: https://v5.db.transport.rest/stops/8000152/departures?stopovers=true&tram=false&bus=false
The Feature 'stopovers' doesn't work anymore. There are show no stops on the way.

**Comment by derhuerst** [comment]
I'll look into it.

**Comment by derhuerst** [comment]
This feature should work again now.

But I will have to remove it soon, as newer versions of the underlying HAFAS API don't support it anymore.
