### ISSUE TITLE
API Playground /location for DB-API has two variables mixed up

### ISSUE THREAD

**Issue by EHandz** [derhuerst/db-rest#24]
Hi,

when using your [API playground](https://petstore.swagger.io/?url=https%3A%2F%2Fv5.db.transport.rest%2F.well-known%2Fservice-desc%0A#/default/get_locations) I noticed that the bools poi and addresses are mixed up in the GUI:

![image](https://user-images.githubusercontent.com/86788690/162064548-07cc9673-6339-41ca-9952-d93fd2a45a99.png)

Thanks a lot for your work, greetings

**Comment by derhuerst** [comment]
Thanks!

**Comment by derhuerst** [comment]
The fix will be deployed to `v5.db.transport.rest` once I have published a new version of `hafas-rest-api@3`.
