### ISSUE TITLE
expose hafas-client's support for age-based tariffs

### ISSUE THREAD

**Issue by derhuerst** [derhuerst/db-rest#25]
[`hafas-client@5.24.0` has added support for age-based tariffs with the DB profile](https://github.com/public-transport/hafas-client/blob/5.24.0/docs/changelog.md#5240), via https://github.com/public-transport/hafas-client/pull/264.

We should expose them here.

**Comment by hakuna-matata-in** [comment]
Hi @derhuerst, I am happy to help. 

Could you please provide me an initial guide on what needs to be integrated into?

**Comment by derhuerst** [comment]
Thanks for offering your help. Are you familiar with `hafas-client` and `hafas-rest-api`? As in, have you looked at the code before?

**Comment by hakuna-matata-in** [comment]
I have tried consuming the vbb-rest apis for creating sample application for educational purpose, apart from it based on the pr mentioned I could understand that a new parameters 'age' & 'agegroup' are introduced & added to request query instead of the default value 'E' for the adult.

**Comment by derhuerst** [comment]
as mentioned in https://github.com/derhuerst/db-rest/issues/29#issuecomment-1451609705:

> this option specific to the DB HAFAS endpoint is currently [buried deep inside `hafas-client`](https://github.com/public-transport/hafas-client/blob/673eb4d6c778ce70e4d451d04bac68f418fd6fa9/p/db/index.js#L165) (which is used by `db-hafas`, which is used here in `db-rest`). it is missing from the documentation (& OpenAPI schema) because it is not added by [`mapRouteParsers()`](https://github.com/derhuerst/db-rest/blob/779e67886bbaf550d52ff6c6e826bd7a866cf851/api.js#L62).
>
> a PR that adds this is very welcome!
