### ISSUE TITLE
Stations api returns the results in an object instead of an array.

### ISSUE THREAD

**Issue by ynsp** [derhuerst/db-rest#26]
The[ Stations endpoint](https://petstore.swagger.io/?url=https%3A%2F%2Fv5.db.transport.rest%2F.well-known%2Fservice-desc%0A#/default/get_stations) returns the results as an object instead of an array, as is stated in the documentation.

Is this something we should consider moving forward?

**Comment by derhuerst** [comment]
Thanks for reporting this.

I think I accidentally caused the discrepancy between the OpenAPI spec and the actual implementation in cf8a00d. I will adapt the OpenAPI spec accordingly.

In a follow-up major version of `db-rest` (`6` a.k.a. `v6.db.transport.rest`), we can change the implementation back to use an array, which I'd say matches the intuitive expectation of what `/stations` returns better.

**Comment by derhuerst** [comment]
The changes in 4086515 should now be live on `https://v5.db.transport.rest`. 🚀
