### ISSUE TITLE
Make rate-limit configurable

### ISSUE THREAD

**Issue by McToel** [derhuerst/db-rest#28]
Hey,
I use this rest API in a project of mine. I am using the docker image. In order to support more traffic on my website (https://bahnvorhersage.de), I need to increase the rate limit (or disable it) at some point in time. Is there currently any way to do this? If not, I would like to suggest making it configurable via an environment variable.

Thanks a lot for providing this simple to set up and beautifully working API

**Comment by derhuerst** [comment]
What does it look like when you're running into the rate limits?

`db-rest` itself doesn't have a rate limit; The limit stated on `https://{v5,v6}.db.transport.rest` ("There's a rate limit of 100 requests/minute (burst 150 requests/minute) set up.") is enforced by the reverse proxy, which is not part of `db-rest`.

The other possible limit you're running into is that the DB HAFAS API rate-limits and/or blocks your server's IP address(es).

**Comment by derhuerst** [comment]
Please re-open if you want to discuss that the DB HAFAS API rate-limits your API's IP address.
