### ISSUE TITLE
Error at `GET /journeys`  with longitude/latitude

### ISSUE THREAD

**Issue by martindotlindner** [derhuerst/db-rest#3]
The API works fine to get journeys with Station IDs, but when using lat/lng the following error massage occur: `"error":true,"msg":"invalid location type: location"`. Same with the second example `curl 'https://1.db.transport.rest/journeys?from=008004158&to.name=Atze%20Musiktheater&to.latitude=52.543333&to.longitude=13.351686'`.

Is it possible to solve this error or is there any other possibility to get journey information from addresses/coordinates without using Station IDs.

**Comment by derhuerst** [comment]
The docs were wrong, I've adapted them accordingly.

If you want to query journeys from/to an address, use `to.address` instead of `to.name`.
