### ISSUE TITLE
API returns no delays while DB Navigator shows delays

### ISSUE THREAD

**Issue by JohannesGandhi** [derhuerst/db-rest#42]
I am raising this issue since the [readme](https://github.com/derhuerst/db-rest/blob/6/docs/readme.md) reads *[...]it returns whatever data the DB Navigator app shows [...]* and I made at least in one instance a different observation.

I adapted the curl command from the [Getting Started guide](https://github.com/derhuerst/db-rest/blob/6/docs/getting-started.md#3-fetch-journeys-from-a-to-b) as follows to retrieve a journey **that was 2h in the past** (not sure if this is relevant)
`curl 'https://v6.db.transport.rest/journeys?from=8004084&to=8000261&departure=today+7:41pm&results=1' -s | jq`
and got the following result, showing delays of `null` and planned=actual times:
```
          "departure": "2024-02-28T19:41:00+01:00",
          "plannedDeparture": "2024-02-28T19:41:00+01:00",
          "departureDelay": null,
          "arrival": "2024-02-28T20:18:00+01:00",
          "plannedArrival": "2024-02-28T20:18:00+01:00",
          "arrivalDelay": null,
```

However, the DB Navigator shows the times as follows, so **with** a delay:
planned: 19:41 - 20:18
actual: 19:57 - 20:35

Note that I queried the api as well as the app several times over a period of at least 30mins and always got the same result.

Is this a known issue? If so, are there some rules or patterns to it so one can work around it?

**Comment by olech2412** [comment]
Hi, I've had some experience with the API by now but of course I don't know it as well as the developer, so everything I'm saying now should be taken with a grain of salt. 

I believe that the 2 hours in the past could play a role. At about 10:10 p.m., I checked your queries in the DB Navigator and the API and can't see any delay in either. Have you perhaps saved a ticket for exactly the connection in the navigator? In my experience, the ticket sometimes displays more and longer information in this regard than via the normal search (that's why i'm asking). As I said, in my review, both systems provided the same answer.

**Comment by JohannesGandhi** [comment]
Hi! You are right! Now the navigator app doesn't show the delay for me anymore either.
So probably it's some sort of caching in the app while the api doesn't cache (for that long)?

Do we know after what time delays start disappearing? There doesn't seem to be a fixed time, since I can still see a delay on a train from 6:18pm, which departed (and arrived) way earlier than the 7:41pm train.

**Comment by olech2412** [comment]
Well, I can't give you a specific time, but the train you mean left at 18:18 or 18:21 but arrived at 21:43. Therefore, I suspect that this is still in the time span, maybe the value is about an hour. It can't be due to caching in this case, because I also still see this entry

**Comment by olech2412** [comment]
> Well, I can't give you a specific time, but the train you mean left at 18:18 or 18:21 but arrived at 21:43. Therefore, I suspect that this is still in the time span, maybe the value is about an hour. It can't be due to caching in this case, because I also still see this entry

Sorry, a bit vague. I mean, he arrives at the final destination station at 9:43 p.m

**Comment by derhuerst** [comment]
This is something that neither `db-rest` nor its underlying library [`db-hafas`](https://github.com/public-transport/db-hafas) (which in turn is just a thin wrapper around [`hafas-client`'s DB profile](https://github.com/public-transport/hafas-client/tree/6.2.2/p/db)) can influence. At some point, DB's API stops returning realtime data (delays, cancellations) for past events; This has been known for a while: https://github.com/public-transport/hafas-client/issues/256 .

> it returns whatever data the DB Navigator app shows

This is probably wrong by now, given that the DB Navigator app switched to a new set of APIs with [their big rewrite/redesign](https://www.heise.de/news/Deutsche-Bahn-bringt-neuen-DB-Navigator-nach-und-nach-auf-die-Smartphones-9312701.html).

The statement applies to their old app. Most of the realtime data should still be the same, but it's not exactly the same API anymore.

**Comment by JohannesGandhi** [comment]
Thanks for the info and references!
Do we know which APIs the new DB Navigator is using and if we can use them as well? Is it the timetables API?
They need to give third parties the possibility to query their data, too. So they should be available to everyone.

In regard to the original issue, maybe it could be mentioned somewhere, that real time data is only available for a short time after the train's arrival and that this API might return differing results to the new navigator. Ie in the getting started guide.

**Comment by derhuerst** [comment]
> Do we know which APIs the new DB Navigator is using and if we can use them as well? Is it the timetables API?

I don't know. Likely @marudor or @vkrause know.

> They need to give third parties the possibility to query their data, too. So they should be available to everyone.

I would like them to give everyone access to this API too, but do they really need to, as in must? There is a relevant ruling by the German competition/antitrust regulation office ([announcement](https://www.bundeskartellamt.de/SharedDocs/Meldung/DE/Pressemitteilungen/2022/20_04_2022_Bahn.html), [actual document](https://www.bundeskartellamt.de/SharedDocs/Entscheidung/DE/Entscheidungen/Missbrauchsaufsicht/2023/B9-144-19.html)).

> In regard to the original issue, maybe it could be mentioned somewhere, that real time data is only available for a short time after the train's arrival and that this API might return differing results to the new navigator. Ie in the getting started guide.

PR welcome!

**Comment by marudor** [comment]
The current Navigator (also called Vendo) still uses HAFAS in the back, but has its own abstraction.
The old Navigator is now the Business Navigator and has the same Information the current (consumer) Navigator has.

**Comment by marudor** [comment]
And DB does not need to give everyone access nor in the format DB Navigator uses.
In the DB API Marketplace they have several APIs as (DB Netz) or (Transporteure)
Those fulfill the current requirement. (I wish they would just open up)
https://developers.deutschebahn.com/db-api-marketplace/apis/product

**Comment by JohannesGandhi** [comment]
I didn't mean that they **must** provide access. I just figured they kind of had to for third parties like app developers.
But apparently only other railway companies that share the tracks with DB get access to the good stuff (RIS::Journeys API, I missed this one so far. Thanks for providing the link). 
Now I'm confused as to why we get access to HAFAS but not RIS::Journeys. While researching for the PR I found [this](https://github.com/public-transport/hafas-client/blob/6/readme.md#background) link which didn't help my confusion.

@derhuerst I created #43 to add some info to the docs. With that we can close this issue imho. Or we can also close it as not planned.

Sorry for off-topic, but since I seem to got the experts here:
There is no service/project for tracking and visualizing **delays of specific journeys over time** yet, is there? Because that's what I'm trying to do.

**Comment by marudor** [comment]
Technically we do not get acess to HAFAS. It's just that a very known source of information (DB Navigator, old/new/business, does not matter) has HAFAS as backend and we spent time to reverse engineer it.
We also have some projects that have access to RIS::Journeys for instance bahn.expert (example: https://bahn.expert/details/ICE%20374/2024-02-29T19:43:37.763Z/?profile=db&station=8500010&journeyId=5da6e29d-d7fa-3113-89d8-6336a2f6f702)
There are salso some DB projects that use RIS::Journeys and have a website (therefore a public API, we're techically not allowed to use it, but who cares)
One example would be DB Regio Zugportal (https://zugportal.de/pages/travel-search/travel-information/c139ef83-fdc4-33bb-b51b-dc4b179ac53d)

About your off-topic question: Not that I know, but I'm not that informed about things.
You will most likely want to use RIS::Journeys for that. I hinted you at possible ways to access it but can not provide any furhter information how to use it.

**Comment by derhuerst** [comment]
remotely related: https://github.com/iRail/iRail/issues/497

**Comment by derhuerst** [comment]
Even though the problems discussed in this thread are not solved, I currently don't see practical ways to tackle them, so I'll close this Issue.

If something has changed, or if you or anyone has a new perspective on this, don't hesitate to comment and I'll reopen it.
