### ISSUE TITLE
Planned departure in addition live-departure in response?

### ISSUE THREAD

**Issue by lud-hu** [derhuerst/db-rest#5]
Hi,

since you mentioned your public API [here](https://github.com/kennell/schiene/issues/14#issuecomment-443785483) I've been playing around with it a little.
I want to use it in a home automation platform for displaying a state card with the current next departures from my defined train station with the needed information and throwing notifications for defined connections when there is a delay. 
Basically it should look like this:

S2   Munich         17:35 +2
S2   Munich         17:45 +0
S2   Munich         17:55 +4

I get all information I need from the response of the /stations/:id/departures endpoint. But I recognized that the timestamp given in "when" property of the response is the time of the departure with the delay already taken into account. I want to display the originally planned departure time and add the delay with a '+'.
Would it be reliable to just subtract the delay from the timestamp?
Or do you get the planned departure time from the db API and can forward it as "planned_departure" or something similar?
This might be important if i want to check for a predefined connection (e.g. the one at 17:35) without having to make an extra api request.

Thanks for your great work!

**Comment by derhuerst** [comment]
> Would it be reliable to just subtract the delay from the timestamp?

Yes. As reliable as that data coming from HAFAS at least.

The reason `when` includes the delay is that, when in doubt, if you don't implement your app properly, you will have realtime data *by default*.

> Or do you get the planned departure time from the db API and can forward it as "planned_departure" or something similar?

[We're planning to use `realtimeDeparture`/`realtimeArrival` & `scheduledDeparture`/`scheduledArrival` in the future.](https://github.com/public-transport/friendly-public-transport-format/issues/61#issue-374516777)

**Comment by derhuerst** [comment]
Please reopen if you have more questions.
