### ISSUE TITLE
Can I work on your documentation?

### ISSUE THREAD

**Issue by sunkanmii** [derhuerst/db-rest#56]
Hey! 👋🏾

My name is Sunkanmi, and I'm a Technical Writer looking to contribute to API documentation on Github. Is it possible for me to submit a PR for Swagger documentation for this API and help refine your Github readme as well?

Let me know if I can get started on this. :)

Hope to speak with you soon!

**Comment by derhuerst** [comment]
Hey!

There already is a [Swagger/OpenAPI document](https://v6.db.transport.rest/.well-known/service-desc), linked both via an HTTP header and in the documentation page (`docs/readme.md`). There is a related [PR](https://github.com/public-transport/hafas-rest-api/pull/15) by @traines-source that fixes and tweaks it, but I still haven't found the time to review and merge it. 🙈

Regarding human-readable documentation: Sure, I appreciate the help. What do you want to improve on, specifically?

**Comment by derhuerst** [comment]
Please re-open if you still want to work on this.
