### ISSUE TITLE
Interface failures

### ISSUE THREAD

**Issue by olech2412** [derhuerst/db-rest#58]
Hello, has anyone else noticed that there have been frequent interface failures on the Deutsche Bahn side recently? With these requests, Deutsche Bahn only gets 500 errors. Is this known and do we know why this is?

I have attached an hour-long recording of when failures occur (see picture).

![image](https://github.com/user-attachments/assets/b7dfc6e5-02f8-4870-bdf6-297efc1d2ff5)

**Comment by derhuerst** [comment]
Yes, this is a known problem with DB's `mgate.exe` HAFAs API. We don't know yet if this is a temporary issue.

- https://matrix.to/#/!fGsJOaXhgnTCFCghEl:matrix.org/$Af-pOVmexMHJ9b5YYtV2ThMl5loSI0oY9YaPhdP3GNU?via=matrix.org&via=kde.org&via=tchncs.de
- https://github.com/schildbach/public-transport-enabler/issues/610
- https://github.com/schildbach/public-transport-enabler/issues/609
- https://github.com/schildbach/public-transport-enabler/issues/573

**Comment by olech2412** [comment]
Thanks for the information and the quick response 🚀
