### ISSUE TITLE
Journey request: 'when' feature doesn't work 

### ISSUE THREAD

**Issue by lrisch** [derhuerst/db-rest#7]
Hi! I want to use the API for a uni project but the when feature doesn't seem to work.

Im not sure if I'm not using it right or if it's really not working. 

For example

https://2.db.transport.rest/journeys?from=008004158&to.address=Berlin - Friedrichsfelde, Sewanstraße 215&to.latitude=52.497282&to.longitude=13.5137&when=12:30&results=1

But the departure time in the results is the current time and not 12:30

**Comment by derhuerst** [comment]
I have renamed the option from `when` to `departure` in the underlying library [`hafas-client`](https://github.com/public-transport/hafas-client).  A fix would be just to rename `when` to `departure` in the code base. Let's see if @petabyteboy will do this in #6. (Of course you're welcome to send a PR by yourself!)

> ```
> https://2.db.transport.rest/journeys?from=008004158&to.address=Berlin - Friedrichsfelde, Sewanstraße 215&to.latitude=52.497282&to.longitude=13.5137&when=12:30&results=1
> ```

Keep in mind that you need to URL-encode special characters, such as spaces (`%20`).

**Comment by derhuerst** [comment]
Please use `departure` instead of `when`. I've fixed the docs in ef058bdebabb37c99394b485c6e696d2d77c3b65.

**Comment by derhuerst** [comment]
Please reopen if you still encounter this issue.
