### ISSUE TITLE
expose firstClass option

### ISSUE THREAD

**Issue by mapl** [derhuerst/db-rest#9]
Please add "class" parameter to be able specify it during POST

**Comment by derhuerst** [comment]
Can you be more specific? Which call/route?

**Comment by mapl** [comment]
Sure, glad that you asked. I just experienced a wrong class number coming back from the query when compared to the actual price amount

I have an example here.

Query:
https://2.db.transport.rest/journeys?from=008011160&to=008002549&&national=false&transfers=0&departure=1556802590

Response excerpt:

"id": "1|268381|0|80|2052019"
"class": 1
"price": {
      "amount": 5X.X,
    }

This price amount is from a class 2 journey, whereas real class 1 price amount is currently 7X.X.

This can be verified by the official reiseauskunft.bahn.de page for this journey,

**Comment by derhuerst** [comment]
The results are only 2nd class right now. We could make `db-rest` support 1st class tickets by passing exposing the [`firstClass` option](https://github.com/public-transport/hafas-client/blob/ed975229086dab33935f0730a3ec61cb097fce53/p/db/index.js#L23-L39) as a query parameter. (We could also add `loyaltyCard` while we're at it.)

The `class` field of the `line` object that you mention above is a technical detail that should not be exposed TBH. I'll remove it in the future.
